from __future__ import annotations

DEFAULT_PHONES = [
    {
        "id": 101,
        "brand": "Samsung",
        "model": "Galaxy A25",
        "category": "phone",
        "price": 92000,
        "currency": "LKR",
        "ram_gb": 8,
        "storage_gb": 256,
        "processor": "Exynos",
        "battery_mah": 5000,
        "camera_mp": 50,
        "rating": 4.4,
        "use_case": ["student", "daily", "camera"],
    },
    {
        "id": 102,
        "brand": "Xiaomi",
        "model": "Redmi Note 13",
        "category": "phone",
        "price": 85000,
        "currency": "LKR",
        "ram_gb": 8,
        "storage_gb": 256,
        "processor": "Snapdragon",
        "battery_mah": 5000,
        "camera_mp": 108,
        "rating": 4.3,
        "use_case": ["daily", "camera", "budget"],
    },
    {
        "id": 103,
        "brand": "Samsung",
        "model": "Galaxy A35",
        "category": "phone",
        "price": 118000,
        "currency": "LKR",
        "ram_gb": 8,
        "storage_gb": 256,
        "processor": "Exynos",
        "battery_mah": 5000,
        "camera_mp": 50,
        "rating": 4.6,
        "use_case": ["student", "daily", "premium-midrange"],
    },
    {
        "id": 104,
        "brand": "Apple",
        "model": "iPhone 13",
        "category": "phone",
        "price": 205000,
        "currency": "LKR",
        "ram_gb": 4,
        "storage_gb": 128,
        "processor": "A15 Bionic",
        "battery_mah": 3240,
        "camera_mp": 12,
        "rating": 4.8,
        "use_case": ["premium", "camera", "daily"],
    },
    {
        "id": 105,
        "brand": "OnePlus",
        "model": "Nord CE 3 Lite",
        "category": "phone",
        "price": 96000,
        "currency": "LKR",
        "ram_gb": 8,
        "storage_gb": 128,
        "processor": "Snapdragon",
        "battery_mah": 5000,
        "camera_mp": 108,
        "rating": 4.2,
        "use_case": ["daily", "budget", "gaming"],
    },
    {
        "id": 106,
        "brand": "Google",
        "model": "Pixel 7a",
        "category": "phone",
        "price": 152000,
        "currency": "LKR",
        "ram_gb": 8,
        "storage_gb": 128,
        "processor": "Tensor G2",
        "battery_mah": 4385,
        "camera_mp": 64,
        "rating": 4.7,
        "use_case": ["camera", "daily", "premium-midrange"],
    },
    {
        "id": 107,
        "brand": "Realme",
        "model": "Narzo 60",
        "category": "phone",
        "price": 72000,
        "currency": "LKR",
        "ram_gb": 8,
        "storage_gb": 128,
        "processor": "Dimensity",
        "battery_mah": 5000,
        "camera_mp": 64,
        "rating": 4.1,
        "use_case": ["budget", "student", "daily"],
    },
    {
        "id": 108,
        "brand": "Samsung",
        "model": "Galaxy S23 FE",
        "category": "phone",
        "price": 189000,
        "currency": "LKR",
        "ram_gb": 8,
        "storage_gb": 256,
        "processor": "Exynos",
        "battery_mah": 4500,
        "camera_mp": 50,
        "rating": 4.6,
        "use_case": ["premium", "camera", "gaming"],
    },
]
